### ISSUE TITLE
drupal.org doesn't let me post to the original issue

### ISSUE THREAD

**Issue by hipnaba** [maoberlehnerdrupal/bower_manager#6]
Hi. Sorry for posting here but drupal.org blocks my submissions for some reason. Anyway ...

Here's a drush command based on Composer Manager.

<a href="https://www.drupal.org/sandbox/hipnaba/2594481">https://www.drupal.org/sandbox/hipnaba/2594481</a>

The commands also have aliases ... tbm and tbjr.

Sorry, I'm not even sure if you're interested in collaborating on this. I believe this is what you had in mind and the Drupal way is collaborate rather than compete :).

I'm also trying to contact the guy that's blocking the Bower project name. I wrote up an issue for him about that this morning, but I guess I forgot to click Save before leaving for work.

**Comment by maoberlehner** [comment]
How do you want to move on? As I can see `tiara-bower-json-rebuild` is very similar to `bower-manager-update`. Do you want to merge the modules?

I'm interested in collaboration but I don't know whats the best way to do it?

**Comment by hipnaba** [comment]
To be honest, I'm not sure. As I said, I'm new to online collaboration, so
not really sure how it all works.

To me it makes sense for the project to be called Bower Manager. As I said,
I'm trying to get the Bower name for the drush wrapper.

Why are you using github instead of drupal.org? Do you want to keep it here
or move the development to drupal.org. If we plan to release the project,
it has to be hosted over there, no?

Now, I'm not sure about the etiquette about all this ... Is stealing stuff
from other projects allowed? I think it makes sense to reuse their aproach
since the workflow is identical.

Sorry, I'm traveling atm so on my phone. Will get back to you later on.

**Comment by maoberlehner** [comment]
I use GitHub because drupal.org sucks in terms of collaborating and git workflow (writing patches) - I love contrib and drupal.org as a platform for contrib modules but for development it just isn't anywhere near GitHub. So if the module gets accepted, development will still happen here but new releases will be pushed to drupal.org (https://www.drupal.org/project/commerce [d8 release] and some other do the same) - at least thats the plan - if there are substantial concerns I'm willing to change my mind.

I created a new issue with a recommendation how we could work it out from here on: https://github.com/maoberlehnerdrupal/bower_manager/issues/7
