### ISSUE TITLE
merge with Tiara Bower Manager

### ISSUE THREAD

**Issue by maoberlehner** [maoberlehnerdrupal/bower_manager#7]
(Tiara Bower Manager: https://www.drupal.org/sandbox/hipnaba/2594481)

As far as i have seen your code looks slightly more "professional" (I like the error throwing and stuff) than mine but it is limited in the way that it is only usable with drush.

I would recommend that we work from this repository as a basis but you implement the `drush_tiara_bower_manager()` function (as a reusable `bower_manager_NAME()` [maybe keep `bower_manager_update()`] function) instead of the current `bower_manager_update` function code.

If you are interested in doing it that way please create a separate feature branch `issue_7` and make your changes in there.

But feel free to recommend a other way of doing it I'm open for your input!

**Comment by hipnaba** [comment]
Absolutely. That's the idea, refactor the actual code to the .module file so it can be used by the module. This was something I just hacked together during downtime at work. 

I'll create the branch and integrate my stuff in there then we'll see what we have. I don't have time to work on this right now but I can make it happen tomorrow.

**Comment by hipnaba** [comment]
This is what I had in mind.

All functions that can run into an error throw exceptions. The code running the whole thing should catch them and display as error messages. An example is the update drush command.

Instead of hook_modules_enabled() we use hook_modules_installed() and hook_modules_uninstalled() because those are the times when we should care about new/removed bower.json files. If a module is only disabled we don't want to remove it's dependencies right away.

I removed the ability to merge specific modules. We always want to rebuild the entire dependency tree to catch version conflicts.

The master bower.json file is by default stored in public://bower/bower.json. The path can be changed in the settings. If it's a multi-site installation each site will have it's own set of enabled modules and themes so we want it to have it's own bower.json. I don't see what the default theme has to do with this. You want to have the same stuff installed when you change your theme because modules can depend on stuff too.

We want the user to be able to edit bower.json if needed. If it doesn't exist we create it with the default data. Property `name` is required for example. But if the user adds stuff in here later on we want to preserve those changes. That's why we merge new data with the original instead of replacing it.

bower_manager_update() now contains only the functionality to generate bower.json. It's easy to add dependencies but how do we remove them? 

How do we handle version conflicts? If one module requires a version not compatible with another module.

I'm not sure if using my other project makes sense. It's just a drush wrapper for BowerPHP. We could just depend on BowerPHP here and use it directly. How do we handle this dependency. Do we depend on Composer Manager to pull in BowerPHP?

I'm not sure about the naming scheme. If you feel that variable or function names could be improved, feel free to do so. Docs too, I'm a terrible writer :).

**Comment by maoberlehner** [comment]
I think removing dependencies is a pretty hard thing to do in a bullet proof way - I think the only way to do it in a reliable way would be if the user is not allowed to modify the target bower.json - If I enable a Drupal module with dependencies and disable it afterwards, the dependencies stay enabled - so I think this behaviour would be OK in our case too?

I think there is now perfect solution to deal with version conflicts, thats a general bower / flat dependency tree problem - so I think the best we can do is to default to the newest provided version and display a Drupal warning message?

**Comment by hipnaba** [comment]
Bower's list command returns the list of installed packages with the ones not used having the label 'extraneous'. Since the directory name is the same as the name of the package we can just delete them. They were installed with bower and not needed anymore, I think it would be safe to delete them. There's an issue to implement the prune command [here](https://github.com/Bee-Lab/bowerphp/issues/23) but doesn't seem it'll get done. Obviously I'd like to do some testing with it.

The thing about versions sounds reasonable for a start. We need to check how to resolve the versions. Is ~2.1 the same as 2.1.\* ... get them all to a form we can compare. Can we use [version_compare](http://php.net/manual/en/function.version-compare.php) here or do we need to implement our own compare function? Then we find the newest version, put that in bower.json and warn the user about what we did.

**Comment by maoberlehner** [comment]
I created separate issues for removing of dependencies https://github.com/maoberlehnerdrupal/bower_manager/issues/10 and dealing with version conflicts https://github.com/maoberlehnerdrupal/bower_manager/issues/11

(I like to have many small separate issues instead of big complex ones - I hope that's ok)
